typography_spectrum: 0.885689037386328
content_rating:
  adult: false
color:
  brandStrength: 0.9078370430506766
  lightness: 0.5432251603342593
  saturation: 0.3781747599132359
  rhythmicContrast: 0.6235807875636965
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.2786898850463331
analytics:
  google: UA-41841548-14
  facebook: "<!-- Facebook Pixel Code --> <script> !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod? n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n; n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0; t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window, document,'script','https://connect.facebook.net/en_US/fbevents.js');  fbq('init', '483982748400304'); fbq('track', \"PageView\");</script> <noscript><img height=\"1\" width=\"1\" style=\"display:none\" src=\"https://www.facebook.com/tr?id=483982748400304&ev=PageView&noscript=1\" /></noscript> <!-- End Facebook Pixel Code -->"
author:
  email: info@bbuzz.me
  url: bbuzz.me
  name: The bbuzz.me Team
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/bfe0da86-f112-4626-8634-6c08fad48ab7.png'
name: bbuzz.me
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf6a3324-9aab-4f28-9d54-702043142cdc.png'
title: The Blue Magazine
